version: '3'
services:
  node-server:
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root  
